config/routes.rb
Grocer::Engine.routes.draw do
  resources :exports, only: [:create, :index, :new, :show]
end

app/models/grocer.rb
module Grocer
  def self.table_name_prefix
    'grocer_'
  end
end

app/models/grocer/application_record.rb
module Grocer
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/grocer/config.rb
module Grocer
  class Config
    attr_writer :baseurl, :export_dir, :jar, :metadata_template, :predicates

    # Fedora baseurl, defaults to ActiveFedora settings
    def baseurl
      @baseurl ||= "#{af_config[:url]}/#{af_config[:base_path]}"
    end

    # Directory to export to, defaults to '/pub/export'
    def export_dir
      @export_dir ||= '/pub/export'
    end

    # Bag metadata template, defaults to '[export_dir]/metadata.yml'
    def metadata_template
      @metadata_template ||= "#{export_dir}/metadata.yml"
    end

    # Fedora Import/Export JAR file, defaults to '[export_dir]/export.jar'
    def jar
      @jar ||= "#{export_dir}/export.jar"
    end

    # Predicates that define resource membership, defaults to 'pcdm:hasMember,ldp:contains'
    def predicates
      @predicates ||= 'http://pcdm.org/models#hasMember,http://www.w3.org/ns/ldp#contains'
    end

    private

    def af_config
      ActiveFedora.config.credentials
    end
  end
end

app/models/grocer/export.rb
module Grocer
  class Export < ApplicationRecord
    validates :pid, presence: true, uniqueness: true

    def running!(job_pid)
      self.job = job_pid
      self.status = 'running'
      save!
    end

    def success!
      self.job = nil
      self.status = 'success'
      self.last_success = Time.current
      save!
    end

    def error!(log)
      self.job = nil
      self.status = 'error'
      self.last_error = Time.current
      self.logfile = log
      save!
    end
  end
end

app/controllers/grocer/exports_controller.rb
module Grocer
  class ExportsController < ApplicationController
    before_action :set_export, only: [:show]

    # GET /exports
    def index
      @exports = status ? Export.where(status: status).page(page) : Export.page(page)
      @counts = Export.group(:status).count
    end

    # GET /exports/1
    def show; end

    # GET /exports/new
    def new
      @export = Export.new
    end

    # POST /exports
    def create
      @export = Export.new(export_params)

      if @export.save
        Grocer::ExportJob.perform_later(@export.pid, @export.ark)
        redirect_to @export, notice: 'Export was successfully created.'
      else
        render :new
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_export
      @export = Export.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def export_params
      params.require(:export).permit(:pid, :job, :status, :last_error, :last_success, :logfile,
                                     :page, :ark)
    end

    def page
      params[:page]
    end

    def status
      params[:status]
    end
  end
end

app/helpers/grocer/exports_helper.rb
module Grocer
  module ExportsHelper
  end
end

app/views/grocer/exports/_form.html.erb
<%= form_for(export) do |f| %>
  <% if export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(export.errors.count, "error") %> prohibited this export from being saved:</h2>

      <ul>
      <% export.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %>
    <%= f.text_field :pid %>
  </div>

  <div class="field">
    <%= f.label :job %>
    <%= f.number_field :job %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :last_error %>
    <%= f.datetime_select :last_error %>
  </div>

  <div class="field">
    <%= f.label :last_success %>
    <%= f.datetime_select :last_success %>
  </div>

  <div class="field">
    <%= f.label :logfile %>
    <%= f.text_field :logfile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grocer/exports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Summary</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @counts.each do |status, count| %>
      <tr>
        <td><%= count %></td>
        <td>
          <% if status == params[:status] %>
            <b><%= status %></b>
          <% else %>
            <%= link_to status, exports_path(status: status)  %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th><%= Grocer::Export.count %></th>
      <th>
        <% if params[:status] %>
          <%= link_to 'all', exports_path %>
        <% else %>
          all
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<h1>Exports</h1>

<table>
  <thead>
    <tr>
      <th>Pid</th>
      <th>Status</th>
      <th>Last error</th>
      <th>Last success</th>
      <th>Logfile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exports.each do |export| %>
      <tr>
        <td><%= export.pid %></td>
        <td>
          <%= export.status %>
          <% if export.job %>(<%= export.job %>)<% end %>
        </td>
        <td><%= export.last_error %></td>
        <td><%= export.last_success %></td>
        <td><%= export.logfile %></td>
        <td><%= link_to 'Show', export %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @exports %>
<%= link_to 'New Export', new_export_path %>

app/views/grocer/exports/new.html.erb
<h1>New Export</h1>

<%= render 'form', export: @export %>

<%= link_to 'Back', exports_path %>

app/views/grocer/exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @export.pid %>
</p>

<p>
  <strong>Job:</strong>
  <%= @export.job %>
</p>

<p>
  <strong>Status:</strong>
  <%= @export.status %>
</p>

<p>
  <strong>Last error:</strong>
  <%= @export.last_error %>
</p>

<p>
  <strong>Last success:</strong>
  <%= @export.last_success %>
</p>

<p>
  <strong>Logfile:</strong>
  <%= @export.logfile %>
</p>

<%= link_to 'Back', exports_path %>